-- Insert Physics chapters
INSERT INTO contest_chapter (title, subject) VALUES
('Units & Dimensions', 'Physics'),
('Motion in One Dimension', 'Physics'),
('Motion in Two Dimensions (Projectile Motion)', 'Physics'),
('Laws of Motion', 'Physics'),
('Work, Power & Energy', 'Physics'),
('Centre of Mass', 'Physics'),
('Rotational Motion', 'Physics'),
('Gravitation', 'Physics'),
('Oscillations (SHM)', 'Physics'),
('Waves (Sound & Mechanical)', 'Physics'),
('Kinetic Theory of Gases', 'Physics'),
('Thermodynamics', 'Physics'),
('Heat Transfer', 'Physics'),
('Electrostatics', 'Physics'),
('Current Electricity', 'Physics'),
('Capacitance', 'Physics'),
('Moving Charges & Magnetism', 'Physics'),
('Magnetism & Matter', 'Physics'),
('Electromagnetic Induction', 'Physics'),
('Alternating Current', 'Physics'),
('Ray Optics', 'Physics'),
('Wave Optics', 'Physics'),
('Dual Nature of Matter & Radiation', 'Physics'),
('Atoms & Nuclei', 'Physics'),
('Semiconductor Electronics', 'Physics'),
('Communication Systems', 'Physics');

-- Insert Maths chapters
INSERT INTO contest_chapter (title, subject) VALUES
('Sets, Relations & Functions', 'Maths'),
('Complex Numbers', 'Maths'),
('Quadratic Equations', 'Maths'),
('Sequences & Series', 'Maths'),
('Binomial Theorem', 'Maths'),
('Permutations & Combinations', 'Maths'),
('Mathematical Induction', 'Maths'),
('Matrices & Determinants', 'Maths'),
('Probability', 'Maths'),
('Statistics', 'Maths'),
('Limits & Continuity', 'Maths'),
('Differentiation', 'Maths'),
('Application of Derivatives', 'Maths'),
('Indefinite Integrals', 'Maths'),
('Definite Integrals', 'Maths'),
('Differential Equations', 'Maths'),
('Straight Lines', 'Maths'),
('Circles', 'Maths'),
('Parabola', 'Maths'),
('Ellipse', 'Maths'),
('Hyperbola', 'Maths'),
('Vectors', 'Maths'),
('Three-Dimensional Geometry', 'Maths'),
('Trigonometric Ratios & Identities', 'Maths'),
('Trigonometric Equations', 'Maths'),
('Properties of Triangles', 'Maths'),
('Inverse Trigonometric Functions', 'Maths'),
('Heights & Distances', 'Maths');
