# Generated by Django 5.2.4 on 2025-08-04 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('MATH', 'mathematics'), ('PHYSICS', 'physics')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=20)),
                ('is_rated', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('subject', models.CharField(choices=[('MATH', 'mathematics'), ('PHYSICS', 'physics')], max_length=20)),
                ('statement', models.TextField()),
                ('type', models.CharField(choices=[('SCQ', 'Single Correct'), ('MCQ', 'Multiple Correct'), ('INT', 'Integer Type')], max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='contest.contest')),
            ],
        ),
    ]
