# Generated by Django 5.2.4 on 2025-08-04 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('subject', models.CharField(choices=[('Physics', 'Physics'), ('Maths', 'Maths')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(default='A'),
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='contest.chapter'),
        ),
        migrations.RenameModel(
            old_name='Contest',
            new_name='Quiz',
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user_answer', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('time_taken', models.FloatField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.quiz')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'contest', 'question')},
            },
        ),
    ]
