# Generated by Django 5.2.4 on 2025-08-08 17:23

import contest.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_chapter_question_correct_answer_question_chapter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
                ('solved_count', models.PositiveIntegerField(default=0)),
                ('penalties', models.IntegerField(default=0)),
                ('old_rating', models.IntegerField(blank=True, null=True)),
                ('new_rating', models.IntegerField(blank=True, null=True)),
                ('rating_change', models.IntegerField(blank=True, null=True)),
                ('is_virtual', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FINALIZED', 'Finalized'), ('DQ', 'Disqualified')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='quiz',
            name='penalty_per_wrong',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='points_rewarded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_value',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contest/image', validators=[contest.validators.validate_file_size])),
                ('captions', models.CharField(blank=True, max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contest.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='contest.question')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='contest.questionoption'),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('base_points', models.PositiveIntegerField(default=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quizzes',
            field=models.ManyToManyField(blank=True, related_name='questions', through='contest.QuizQuestion', to='contest.quiz'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('contest__isnull', False)), fields=('contest',), name='uq_question_contest_order'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='contest.quiz'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'question')},
        ),
        migrations.AddConstraint(
            model_name='quizresult',
            constraint=models.UniqueConstraint(condition=models.Q(('is_virtual', False)), fields=('user', 'quiz'), name='uniq_live_result_per_user_quiz'),
        ),
    ]
