# Generated by Django 5.2.4 on 2025-09-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_rename_quizresult_userquizresult_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquizresult',
            old_name='solved_count',
            new_name='correct_answers',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='base_points',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
