# Generated by Django 5.2.4 on 2025-09-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='matches',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
